export enum BlogStatus {
  PUBLISHED = "PUBLISHED",
  DRAFT = "DRAFT",
}

export enum BlogCategory {
  FOOD = "FOOD",
  TRAVEL = "TRAVEL",
  FINANCE = "FINANCE",
  ENTREPRENEURSHIP = "ENTREPRENEURSHIP",
  TECHNOLOGY = "TECHNOLOGY",
  HEALTH = "HEALTH",
  REALESTATE = "REAL ESTATE",
  ECOMMERCE = "E-COMMERCE",
  HR = "HUMAN RESOURCE",
  MANUFACTURING = "MANUFACTURING",
  EDUCATION = "EDUCATION",
  BUSINESS = "BUSINESS",
  SPORTS = "SPORTS",
  ART = "ART",
  CULTURE = "CULTURE",
  OTHER = "OTHER"
}
